import torch
from transformers import AutoTokenizer, AutoModelForCausalLM

model_id = "gpt2"

device = "cuda" if torch.cuda.is_available() else "mps"  # checking if a GPU is available and setting the device accordingly

# Step 1. Load GPT-2 model and tokenizer.
"""
YOUR CODE HERE (~2 lines of code)
"""

tokenizer = AutoTokenizer.from_pretrained(model_id)  # loading the GPT-2 tokenizer using the Hugging Face transformers library
model = AutoModelForCausalLM.from_pretrained(model_id).eval().to(device)  # loading the GPT-2 model using the Hugging Face transformers library

# Step 2. tokenize the prompt, then use model.generate() to generate text, then print the text
prompt = "Hi my name"

"""
YOUR CODE HERE (~3-6 lines of code)
"""

input_tokens = tokenizer(prompt, return_tensors="pt").to(model.device)  # tokenizing the prompt and returning the token IDs as a PyTorch tensor

#print(input_tokens)  # printing the token IDs of the prompt

output_tokens = model.generate(
    **input_tokens,  # passing the token IDs of the prompt to the model for text generation
    max_new_tokens=10,  # setting the maximum number of new tokens to generate
    do_sample=False  # enabling sampling for text generation, greedy is used, which picks highest possibility as the next token

)

output_tokens  # printing the output token IDs generated by the model

# Step 3: Write a helper function that wraps model.generate for greedy decoding,
# then test it on multiple prompts to observe repetition patterns.

tests = ["Once upon a time", "What is 2+2?", "Suggest a party theme."]

def generate(model, tokenizer, prompt, max_new_tokens=32):
    """
    YOUR CODE HERE (~5 lines of code)
    """
    pass

    enc = tokenizer(prompt, return_tensors="pt").to(model.device)  # tokenizing the prompt and returning the token IDs as a PyTorch tensor
    output = model.generate(
        **enc,
         max_new_tokens=max_new_tokens, 
         do_sample=False,
         pad_token_id=tokenizer.eos_token_id
    )  # generating text using the model with greedy decoding
    return tokenizer.decode(output[0], skip_special_tokens=True)  # decoding the output token IDs back into text and skipping special tokens

for prompt in tests:
    print(f"\n GPT-2 | Greedy")
    print(generate(model, tokenizer, prompt, 80))